[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
autogen-agentchat = ">=0.2,<1.0"
autogen-ext = {extras = ["docker", "openai"], version = "^0.4.3"}
whisperx = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"